### ISSUE TITLE
Is PHP7 release stable?

### ISSUE THREAD

**Issue by slawomir-pryczek** [php-memcached-dev/php-memcached#213] opened 2016-02-02 14:51 UTC
Hi Guys,
I tried to switch to php-memcached on a service where we have like 20-30k request/s and it seems that PHP7 memcached release is having some issues... basically when using persistent connection mode it segfaults like crazy. I tried to switch to normal connections but then other memcached clients using old library under php5.6 were having issues to connect (maybe connections are not fully closed?)

We also made a simple debugging script, on pconnect it segfaults and loose key values (even if key is in cache it randomly returns empty), on normal connect it's much slower than memcache and unstable... connect->set->get takes about 1-30 ms, on the old setup (memcache/php) extension it's preety constant at 1-4ms.

Up to some point it works ok (we build a cluster like setup where we can control traffic send to all nodes), but after traffic gets higher it starts to make issues.

Can this be somehow related to connection handling and are you aware of this issue?

**Comment by mkoppanen** [comment] 2016-02-02 14:53
Hello,

there is no release for PHP7 yet. I am currently working on resolving issues with PHP7 and cleaning up the code. Is the persistent connection issue easy to reproduce? I'll take a look as soon as possible

Thanks,
Mikko

**Comment by slawomir-pryczek** [comment] 2016-02-02 15:14
Aha, that's great i'll see about reproducing the issue and prepare some code

**Comment by slawomir-pryczek** [comment] 2016-02-03 15:38
Hi Mikko, we looked more into the issue... 

Good thing is that the spike problem seems to be networking related. We have just installed php7/lighty on this server and it seems we have some switch problems. That's what was causing spikes in connection times... sorry for confusion.

Now for the segfault issues, we were able to eliminate it by switching to memcache (not d) module found here
https://github.com/websupport-sk/pecl-memcache/tree/NON_BLOCKING_IO_php7
Wasn't able to reproduce it in VM... 

So the only think i know for now ...
1. it disappears after switching memcache*d* to normal connections
2. it also disappears after using memcache (without d) and persistent connections

If i'll find anything else that might help diagnosing issue - will post here.

Thanks.

**Comment by getmo-technology** [comment] 2016-02-05 01:24
@mkoppanen Only waiting to stable version. My unit test are passing. :+1:

**Comment by jonathanpmartins** [comment] 2016-02-05 01:26
@mkoppanen Only waiting for stable release! My unit tests are passing!

**Comment by dzuelke** [comment] 2016-02-05 12:29
Let me know if there's anything I can do to help with PHP 7, @mkoppanen !

**Comment by jonathanpmartins** [comment] 2016-02-05 15:36
:+1: ehehhe, oh, the waiting is killing me.

**Comment by mkoppanen** [comment] 2016-02-06 05:10
@dzuelke,

Reviewing #214 would be helpful. Also running your local test suites against that would be a huge help. Been fixing a lot of errors in the existing code and the diff just keeps growing. 

Among other things we had six versions (copy-paste) of different set and get code.

**Comment by mkoppanen** [comment] 2016-02-06 05:13
@slawomir-pryczek,

with PR #214 I am unable to reproduce the persistent connection segfault. In my local environment persistent connections seem to work as expected and valgrind isn't complaining. 

Can you try this branch and see if it solves your issues?

Thanks,
Mikko

**Comment by slawomir-pryczek** [comment] 2016-02-16 21:53
Hi Mikko, sorry for waiting, we were able to do some quick tests with recent code (i saw #214 is merged in php7 branch), with persistent connections - no longer segfaulting, so it seems fixed.

**Comment by ralfbecker** [comment] 2016-03-04 07:51
Any news or timeline for a PHP7 supporting release?

**Comment by jonathanpmartins** [comment] 2016-03-08 15:34
@ralfbecker You can compile it using the php7 branch. See my comment on this issue: https://github.com/php-memcached-dev/php-memcached/issues/194#issuecomment-193823540

**Comment by oerdnj** [comment] 2016-03-09 10:06
@mkoppanen JFTR I got one user reporting BC break in 3.0.0b1, but he refused to report it here and claims the BC break in 3.0.0b1 is deliberate. Are you aware of any BC breaks in 3.0.0b1 (latest git), I haven't found anything in the git log that would suggest so?

**Comment by mkoppanen** [comment] 2016-03-09 12:36
@oerdnj, there is an intentional backwards compatibility break with cas token parameter in certain calls.

**Comment by dzuelke** [comment] 2016-03-09 12:37
Is that documented anywhere? Or a ticket for it?

**Comment by dzuelke** [comment] 2016-03-09 19:32
Ah just saw, it's in `package.xml` only, not in `ChangeLog`.

Any plans for the `3.0.0a1` tag and PECL release? :)

**Comment by slashterix** [comment] 2016-03-10 20:43
@mkoppanen what can I or my company do to help speed up the release of this? I understand you are a busy guy and thank you for all your work here. We are excitedly awaiting this package so we can start using php7 in production and would like to help any way we can.

**Comment by MartialGeek** [comment] 2016-03-11 08:32
Hi!

Is there a release date for the PHP7 version?

Thank you

**Comment by solidspark** [comment] 2016-03-14 22:49
We are eagerly awaiting this release. Let me know how we can assist.

**Comment by dzuelke** [comment] 2016-03-22 23:15
Can you please merge #232 and the following PRs with docs @mkoppanen so I or others can continue work on the changelog?

**Comment by dzuelke** [comment] 2016-03-30 00:01
I've been trying to take a stab at the changelog, @mkoppanen, but unfortunately, the most important changes are all part of one massive commit, a930b41fa138a55b976c55e21157e57b09355343, with no descriptive commit message or comments.

**Comment by matts2cant** [comment] 2016-06-01 14:32
Bump, any news ?

**Comment by dick9gag** [comment] 2016-06-08 17:12
one potential blocker to release is #250.
and there are PR #252 for it. hopefully it got reviewed and also got verified to fix #250

**Comment by dictcp** [comment] 2016-06-08 17:13
one potential blocker to release is #250.
and there are PR #252 for it. hopefully it got reviewed and also got verified to fix #250 soon

**Comment by dmitriivoitovich** [comment] 2016-06-20 08:47
Hey guys! Any news about stable release with php7 support? Our OPS team refuse to install any third party builds so we are kind of stuck with migration to php7 because of memcached extension.

**Comment by ralfbecker** [comment] 2016-06-20 08:59
Same here, missing Memcached support stalls PHP 7 migration :(

**Comment by NoodlesNZ** [comment] 2016-06-21 19:54
Ditto here, waiting on this extension before we move to PHP 7, no pressure :)

**Comment by ccovey** [comment] 2016-07-08 17:45
Same, need a stable build before we would want to use in production.

**Comment by jmara** [comment] 2016-07-27 08:02
Hey there,

any progress or ETA with the final release?

Cheers,
Jan

**Comment by jonathanpmartins** [comment] 2016-08-02 01:57
I really really migrated all my caches to super REDIS! heheheheh

**Comment by matts2cant** [comment] 2016-08-02 08:51
@jonathanpmartins: Yup, same here :)

**Comment by dzuelke** [comment] 2016-08-17 00:11
#271 has some release notes, @mkoppanen

**Comment by oligriffiths** [comment] 2016-08-17 19:05
@mkoppanen Can you provide further details on the BC break with the `cas` method and where this is documented please. This took us quite some time to track down.

**Comment by tvlooy** [comment] 2016-09-02 11:43
is the release of the 7 version a time / money issue? It seems like a lot of people need this to migrate to 7, so if all these people would put some money in a jar we could pay someone to do the work. Is setting up a donation thing a good idea?

**Comment by sonyarianto** [comment] 2016-09-04 15:38
or this because everybody should move to Redis? Oh nooo

**Comment by colepatrickturner** [comment] 2016-09-21 18:05
I've found the `php-memcached` package to return incorrect values when using `get($key)` and have since switched back to `Memcache`

**Comment by ficus** [comment] 2016-09-22 21:07
@colepatrickturner what build?  Can you reproduce so as to open a ticket?  Your comment is raining on my parade as is.  Also, curious where does your php-memcache comes from?  Port by kaltura?

**Comment by colepatrickturner** [comment] 2016-09-22 21:17
`php-memcached` installed from apt-get

PHP (FPM) Version: 7.0.11-1+deb.sury.org~trusty+1
Version: 3.0.0a1-13-g6ee96ca+2.2.0-4+donate.sury.org~trusty+3

What I experienced:
Retrieved key #1 (77 characters)
Received result from another key (< 12 characters)

I cross-checked this directly with the memcached daemon `telnet localhost 11211` and found that it was `php-memcached` returning the wrong values. Switched to `php-memcache` (3.0.9~20160311.4991c2f-5+donate.sury.org~trusty+1) because it works.

**Comment by oerdnj** [comment] 2016-09-23 07:56
@colepatrickturner The latest release in the PPA should be `3.0.0a1-57-g4fa2111+2.2.0-1` which is just four commits behind the `php7` branch, so you should try to reproduce with at least that.

I have also just uploaded the currect php7 HEAD build, so even better try with `3.0.0a1-61-g583ecd6+2.2.0-1+deb.sury.org~trusty+1`.

**Comment by colepatrickturner** [comment] 2016-09-23 16:26
@oerdnj the machine I'm using is amd64 which has failed builds for anything greater than 3.0.0a1-13. I'll see if I can reproduce it on another machine and then build from source to the latest version.

P.S. thank you for providing packages!

**Comment by thias** [comment] 2016-12-21 15:01
Not to criticize or anything, but for having run both phpredis and this memcached extension in production with PHP 7.0 for some months, with a relatively simple SET/GET usage, both have their issues. In my opinion "switching to Redis" might not necessarily be the right solution, see https://github.com/phpredis/phpredis/issues/429 - I have been bitten by that one, with some fairly nasty consequences.

Right now I'm still seeing some minor issues with the memcached extension, but at least the issues seem visible (PHP Warnings are triggered) and memcached scales much better than redis on a single system with simple SET/GET usage (Redis is single fork, single thread and easily saturated a single CPU core in my environment).

I'm hoping to have time to debug our issues soon, and report details here, but in the meantime it could be a nice thing to get a proper release of the current code on the php7 branch, maybe marked as beta for now.

**Comment by iBobik** [comment] 2016-12-21 15:48
Good idea to release beta, because it will reach more installs and more testers.

Jan Pobořil
http://honza.poboril.cz/

21. 12. 2016 v 16:01, Matthias Saou <notifications@github.com>:

**Comment by slawomir-pryczek** [comment] 2016-12-21 20:42
Hi Guys, I want to invite you to test my memcached - like server written in go available at:
https://github.com/slawomir-pryczek/FlatDB

Basically in my company we were using memcached modified by me for a long time (like 3-4 years), because of bugs with PHP7 (and also we need something a little different than memcached), i decided to write my own version...  It's used in production for about 200 days without restart, it has much better GC, configurable auto-rebalance which is able to move items between slabs, snapshots, tcp optimizations for high MTU, optimizations for high number of CPU cores, etc.

It has native PHP client using TCP sockets, and the server works on TCP, UDP and HTTP. Easy to install using composer.

The new version has some nice features like sharding and replication for all operations. Sharding and replication is tested using phpunit tests, but not yet in production, we'll be testing that too, soon. If smoeone has any questions let me know.

**Comment by iBobik** [comment] 2016-12-21 23:32
Comment of @slawomir-pryczek seems like a spam. (This project is PHP client for Mencached, not server.)

**Comment by jrchamp** [comment] 2016-12-21 23:37
@iBobik It looks like both a memcached replacement and a native PHP client for an in-memory key-value store. If it's spam then the redis conversation is too.

**Comment by slawomir-pryczek** [comment] 2016-12-22 08:10
@jrchamp yes thanks for the comment, the project is server and client. To help people that have issues with memcached and want to try something what is more like memcached than redis/mongo, and has all features which are missing from simplified memcache extension (which is very good but lacking some features like atomic ops with CAS), plus want good support for very dynamic data (different size, TTLs, etc.).

@iBobik You're here just to say "good idea" and link to your homepage... then, magically i'm "spamming" :) Uh, okay ;)

**Comment by oerdnj** [comment] 2016-12-22 08:14
Because he replied to the issue via email and now stop spamming this issue with other projects please.

**Comment by Intrepidity** [comment] 2016-12-29 12:01
So, 5.6 officially loses support in 2 days, 7.0 has been out for 2 years, and still no stable version of this extension, nor any clear answers on what still needs to happen or how we can help? It's an OSS project after all. I'm more than willing to invest some time in getting this to a stable release.

**Comment by oerdnj** [comment] 2016-12-29 12:39
@Intrepidity What are you talking about? PHP 5.6 is security supported until 31 Dec 2018 (e.g. two more full years) and PHP 7.0 was initially released 1 year ago (not two).

**Comment by slawomir-pryczek** [comment] 2016-12-30 00:14
@Intrepidity I have recently spoken with a guy that wrote similar extension for his company as they were having issues with PHP7... you may give it a try, if you need memcached as he seemed very capable
https://github.com/cybozu/php-yrmcds/ so if you can't use that limited memcache extension i linked in 4th post that's probably way to go for now...

**Comment by ChazyTheBest** [comment] 2016-12-30 00:37
So what is the reason for such delay?

**Comment by sodabrew** [comment] 2017-01-24 11:32
The 3.0.0 release will be released Real Soon Now. I'm cleaning up the tickets in preparation.

**Closed by sodabrew** 2017-01-24 11:32 UTC
