### ISSUE TITLE
User-flags related changes cause issues during inheritance

### ISSUE THREAD

**Issue by mkoppanen** [php-memcached-dev/php-memcached#126] opened 2014-01-16 15:35 UTC
More information:

symfony/symfony#9797

https://bugs.php.net/bug.php?id=66331

**Comment by sblmasta** [comment] 2015-01-26 13:46
@mkoppanen When will you repair this error? I still have the runtime notice.
php-memcached build status is failing.

I'm using libmemcached version 1.0.10 and php-memcached 2.2.0  (php 5.5 compiled)

**Comment by hanikesn** [comment] 2015-09-02 09:11
Hi this is still an issue. For example the widely used LswMemcacheBundle (https://packagist.org/packages/leaseweb/memcache-bundle) migrated to the memcache extension, because of that.

**Comment by digitalprecision** [comment] 2015-10-01 18:07
@hanikesn I saw that in their git repo, seems lame to switch APIs just to hack by this issue. Until this is resolved upstream (here), I will add a php version check in my code. This should be fixed asap.

**Comment by mkoppanen** [comment] 2016-01-06 15:50
Looks like this has not been actioned in upstream (https://bugs.php.net/bug.php?id=66331) and is still causing problems in PHP7. I think the sanest approach is to remove the user flags for now and figure out a cleaner way to do it.

Even though I am opposed to hacking around things that are actual bugs in PHP it seems that this is causing issues on our users.

Maybe someone with more experience on the engine could weigh on this? //cc @krakjoe @rlerdorf

**Comment by SjonHortensius** [comment] 2016-01-06 15:54
@mkoppanen I agree, it's too bad PHP doesn't fix their bug, but with the release of PHP7 this issue is becoming a bigger problem. Do you think your [previous suggestion](https://github.com/php-memcached-dev/php-memcached/issues/126#issuecomment-32681337) of creating an additional `getUserFlags()` is still an option?

**Comment by mkoppanen** [comment] 2016-01-17 00:54
Looks like even removing user flags helps with PHP7. I opened a PR against PHP to get this fixed. Let's see how it goes.

**Comment by mkoppanen** [comment] 2016-01-18 05:40
Looks like PR #209 sorts out issues with user flags + inheritance. Does the API seem reasonable?

**Comment by SjonHortensius** [comment] 2016-01-24 14:13
Your change and new API looks fine to me. However, it doesn't seem to fix compatibility with php7; compiling the php7 branch, and overloading the `get()` method still results in an error for me. I'll add a testcase so you can confirm.

The error no longer mentions the user-flags btw.

**Comment by mkoppanen** [comment] 2016-01-25 13:32
@SjonHortensius,

see php/php-src#1729 PR. Looks like the behaviour is expected. This would mean refactoring CAS parameter out as well.

**Comment by SjonHortensius** [comment] 2016-01-26 08:03
Ah, you're right. I forgot about that one. Let's hope a php-core dev can shed some light on that issue

**Comment by mkoppanen** [comment] 2016-02-01 01:21
Resolved in #211, I created a new API for php-memcached. get and getMulti now take a flag (Memcached::GET_EXTENDED), which allows to return both user flags and cas tokens. I am merging #211 shortly (as soon as the merge build passes)

**Comment by jakzal** [comment] 2016-09-21 11:00
#211 fixed the problem. I just tried it on PHP7. Any chance to port the fix back to 2.x?

**Closed** 2017-01-24 06:35 UTC

**Comment by jakzal** [comment] 2017-01-24 09:00
@sodabrew would you mind explaining why's this issue closed?

**Comment by sodabrew** [comment] 2017-01-24 09:23
I'm not planning to make any further php-memcached 2.x releases for PHP 5.x, so if the issue is resolved for php-memcached 3.x (unreleased) for PHP 7.x going forward, so I would consider this resolved.
