### ISSUE TITLE
setByKey() doesnt work with OPT_REMOVE_FAILED_SERVERS

### ISSUE THREAD

**Issue by stangl** [php-memcached-dev/php-memcached#153] opened 2014-10-02 18:29 UTC
memcached ver 2.1.0

setByKey() doesnt use the other online servers on failure on one of three servers. 

set() stores well on another server and returns true. 
setByKey() doesnt store and returns false.

maybe the same problem with all *ByKey() functions

i dont know its a bug or feature. if its a feature it would be nice to have an option to store even on failure. maybe a "strict"-Option to get false on error like now.

i use *ByKey() to store a group of entries on the same machine.

**Comment by sodabrew** [comment] 2017-02-10 21:47
As I marked in #154 I think this is working as intended, but since you mention that get() and getByKey() behave differently, I would agree this is an upstream problem. Closing for now.

**Closed by sodabrew** 2017-02-10 21:47 UTC
