### ISSUE TITLE
Mocking `Memcached` object results in error

### ISSUE THREAD

**Issue by bryanlatten** [php-memcached-dev/php-memcached#168] opened 2015-04-15 17:38 UTC
Love the Memcached extension, looking to do a 'lower'-level integration (which always makes me laugh in a scripting language), which requires some testing. Unfortunately, this does not seem possible with the current 2.2.0 release.

```Declaration of Mock_Memcached_0376aa4c::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)```

Also see: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/192

Currently seen in PHP 5.5+ (tested 5.5.22 / 5.6.7), with phpunit 3.7, 4.4, 4.5

**Comment by mkoppanen** [comment] 2015-04-15 17:39
Duplicate of #126

**Closed by mkoppanen** 2015-04-15 17:39 UTC
