### ISSUE TITLE
Update memcached.ini or change default value for memcached.sess_prefix

### ISSUE THREAD

**Issue by Yuxael** [php-memcached-dev/php-memcached#340] opened 2017-04-26 15:59 UTC
Please update either memcached.ini or php_memcached.c

memcached.ini says:
```
; memcached session key prefix
; valid values are strings less than 219 bytes long
; the default value is "memc.sess.key."
memcached.sess_prefix = "memc.sess.key."
```
while in php_memcached.c there is:
```
MEMC_SESSION_INI_ENTRY("prefix", "memc.sess.", OnUpdateSessionPrefixString, prefix)
```

Personally I'd prefer if you updated the latter to:
```
MEMC_SESSION_INI_ENTRY("prefix", "memc.sess.key.", OnUpdateSessionPrefixString, prefix)
```
for compatibility reasons.

While this is not critical it can cause some headache in an environment with multiple PHP versions.

**Comment by sodabrew** [comment] 2017-06-13 15:51
The default INI file explicitly sets the value to `memc.sess.key` but without a config file it's set to `memc.sess.`, ouch. Someone without a config file will notice a change in hardcoded defaults 🎱  if I adjust the code to match the documentation.

**Comment by sodabrew** [comment] 2017-06-13 15:52
Ping @remicollet this issue will be more apparent since I merged #330, and will need to be addressed before I can release.

**Comment by rlanvin** [comment] 2017-10-10 13:37
> While this is not critical it can cause some headache in an environment with multiple PHP versions.

I just encountered this bug (when working with a mix of PHP5 & PHP7), so yeah I can confirm this - while not critical, it definitely caused some confusion.

**Comment by remicollet** [comment] 2017-10-10 13:44
@sodabrew I agree, memc.sess.key. everywhere seems better

**Closed** 2017-11-21 05:51 UTC
