### ISSUE TITLE
Session replication issues with PHP 7

### ISSUE THREAD

**Issue by jaimievansanten** [php-memcached-dev/php-memcached#299] opened 2017-01-22 14:53 UTC
Hi, 

We're attempting to do an upgrade to PHP 7. We're running some tests to see the stability of Memcached with PHP 7. However we're facing some issues when simulating replication when the primary Memcached node is killed.

To simulate the issue we have created a Docker setup with PHP 7 and memcached compiled from latest `upstream/master`, a simple PHP file to get/set values in Memcached and 2 Memcached-nodes.

Versions
* Apache 2.4.10
* PHP 7.0.14
* libmemcached-dev 1.0.18-4

*memcached.ini*
```ini
extension=memcached.so

[memcached]
; Use session locking
; valid values: On, Off
; the default is On
memcached.sess_locking = Off

; Session spin lock retry wait time in microseconds.
; Be carefull when setting this value.
; Valid values are integers, where 0 is interpreted as
; the default value. Negative values result in a reduces
; locking to a try lock.
; the default is 150000
;memcached.sess_lock_wait = 150000

; The maximum time, in seconds, to wait for a session lock
; before timing out.
; Setting to 0 results in default behavior, which is to
; use max_execution_time.
;memcached.sess_lock_max_wait = 0

; The time, in seconds, before a lock should release itself.
; Setting to 0 results in the default behaviour, which is to
; use the memcached.sess_lock_max_wait setting. If that is
; also 0, max_execution_time will be used.
;memcached.sess_lock_expire = 0

; memcached session key prefix
; valid values are strings less than 219 bytes long
; the default value is "memc.sess.key."
memcached.sess_prefix = "session."

; memcached session consistent hash mode
; if set to On, consistent hashing (libketama) is used
; for session handling.
; When consistent hashing is used, one can add or remove cache
; node(s) without messing up too much with existing keys
; default is Off
memcached.sess_consistent_hash = On

; Allow failed memcached server to automatically be removed
; default is 0
memcached.sess_remove_failed = 1

; Write data to a number of additional memcached servers
; This is "poor man's HA" as libmemcached calls it.
; If this value is positive and sess_remove_failed is enabled
; when a memcached server fails the session will continue to be available
; from a replica. However, if the failed memcache server
; becomes available again it will read the session from there
; which could have old data or no data at all
memcached.sess_number_of_replicas = 1

; memcached session binary mode
; libmemcached replicas only work if binary mode is enabled
memcached.sess_binary = On

; memcached session replica read randomize
memcached.sess_randomize_replica_read = Off

; memcached connect timeout value
; In non-blocking mode this changes the value of the timeout
; during socket connection in milliseconds. Specifying -1 means an infinite timeout.
memcached.sess_connect_timeout = 100

; Session SASL username
; Both username and password need to be set for SASL to be enabled
; In addition to this memcached.use_sasl needs to be on
;memcached.sess_sasl_username = NULL

; Session SASL password
;memcached.sess_sasl_password = NULL

; Set the compression type
; valid values are: fastlz, zlib
; the default is fastlz
;memcached.compression_type = "fastlz"

; Compression factor
; Store compressed value only if the compression
; factor (saving) exceeds the set limit.
;
;  store compressed if:
;    plain_len > comp_len * factor
;
; the default value is 1.3 (23% space saving)
;memcached.compression_factor = "1.3"

; The compression threshold
;
; Do not compress serialized values below this threshold.
; the default is 2000 bytes
;memcached.compression_threshold = 2000

; Set the default serializer for new memcached objects.
; valid values are: php, igbinary, json, json_array, msgpack
;
; json - standard php JSON encoding. This serializer
;        is fast and compact but only works on UTF-8
;        encoded data and does not fully implement
;        serializing. See the JSON extension.
; json_array - as json, but decodes into arrays
; php - the standard php serializer
; igbinary - a binary serializer
; msgpack - a cross-language binary serializer
;
; The default is igbinary if available, then msgpack if available, then php otherwise.
;memcached.serializer = "igbinary"

; Use SASL authentication for connections
; valid values: On, Off
; the default is Off
;memcached.use_sasl = Off

; The amount of retries for failed store commands.
; This mechanism allows transparent fail-over to secondary servers when
; set/increment/decrement/setMulti operations fail on the desired server in a multi-server
; environment.
; the default is 2
;memcached.store_retry_count = 2

[session]
; Use memcache as a session handler
session.save_handler = memcached

; session.name specifies the name of the session which is used as cookie name. It should only contain alphanumeric
; characters. Defaults to PHPSESSID. See also session_name().
;session.name = "PHPSESSID"

; session.gc_maxlifetime specifies the number of seconds after which data will be seen as 'garbage' and potentially
; cleaned up. Garbage collection may occur during session start (depending on session.gc_probability and
; session.gc_divisor). The default is 1440.
;session.gc_maxlifetime = 1440

; Defines a comma separated of server urls to use for session storage,
; for example "tcp://host1:11211, tcp://host2:11211".
; Each url may contain parameters which are applied to that server,
; they are the same as for the Memcache::addServer() method.
; For example "tcp://host1:11211?persistent=1&weight=1&timeout=1&retry_interval=15"
session.save_path = "memcached-1:11211,memcached-2:11211"
```

*src/index.php*
```php
<?php

$libmemcachedVersion = `php --info | awk '/^libmemcached version => / {print $4;}'`;
header('X-Libmemcached-Version: ' . $libmemcachedVersion);

session_start();

echo 'The session has started: ' . session_id() . PHP_EOL;

echo 'Key values in the session:'. PHP_EOL;
foreach ($_SESSION as $key => $value) {
    echo '    ' . $key . ' = ' . $value . PHP_EOL;
}

if (count($_GET) > 0) {
    echo 'Adding to the session:' . PHP_EOL;
    foreach ($_GET as $key => $value) {
        $_SESSION[$key] = $value;
        echo '    ' . $key . ' = ' . $value . PHP_EOL;
    }
}

session_write_close();
```

Simulating a primary node failure results in the following:

*Output*
```
PLAY [test php7 pecl primary and replica node failure] *************************

TASK [common : cleanup docker-compose project] *********************************
task path: poc-php-memcached-sessions/ansible/roles/common/tasks/main.yml:2
changed: [localhost] => {"actions": {}, "changed": true}

TASK [common : initialize brand new docker-compose project] ********************
task path: poc-php-memcached-sessions/ansible/roles/common/tasks/main.yml:8
changed: [localhost] => {"ansible_facts": {"memcached-1": {"pocphpmemcachedsessions-memcached-1": {"cmd": ["memcached", "-vv"], "image": "memcached:alpine", "labels": {"com.docker.compose.config-hash": "15248ca9fc278bc86451f857e8bcaa9f1cf3e664aa14c75b122567779cb513ec", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "memcached-1", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.2", "IPPrefixLen": 16, "aliases": ["c9ee3c1dc38a", "memcached-1"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:02"}}, "state": {"running": true, "status": "running"}}}, "memcached-2": {"pocphpmemcachedsessions-memcached-2": {"cmd": ["memcached", "-vv"], "image": "memcached:alpine", "labels": {"com.docker.compose.config-hash": "4316db7e75ec1b9e893b3a49cd3445a0843719161c35de631aed8174934317a5", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "memcached-2", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.3", "IPPrefixLen": 16, "aliases": ["49f288bd9703", "memcached-2"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:03"}}, "state": {"running": true, "status": "running"}}}, "php-app-1": {"pocphpmemcachedsessions-php-app-1": {"cmd": ["apache2-foreground"], "image": "pocphpmemcachedsessions_php-app-1", "labels": {"com.docker.compose.config-hash": "9f7e6d8f49ebef0f4972f76aad82e3c466e491d53f1446f4b1deb8309057eacb", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "php-app-1", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.6", "IPPrefixLen": 16, "aliases": ["f9644b558b2e", "php-app-1"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:06"}}, "state": {"running": true, "status": "running"}}}, "php-app-2": {"pocphpmemcachedsessions-php-app-2": {"cmd": ["apache2-foreground"], "image": "pocphpmemcachedsessions_php-app-2", "labels": {"com.docker.compose.config-hash": "f94e8851048ceab17976e29f4b3f70993da472d6f958ab7f070f93fdf9531b6e", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "php-app-2", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.7", "IPPrefixLen": 16, "aliases": ["php-app-2", "17a2b1f2a7f6"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:07"}}, "state": {"running": true, "status": "running"}}}, "php-app-3": {"pocphpmemcachedsessions-php-app-3": {"cmd": ["apache2-foreground"], "image": "pocphpmemcachedsessions_php-app-3", "labels": {"com.docker.compose.config-hash": "62556a78edef02208779ede861d28c5246bb451d480615ea3717496bf8f6402b", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "php-app-3", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.5", "IPPrefixLen": 16, "aliases": ["9873e0e5f8d8", "php-app-3"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:05"}}, "state": {"running": true, "status": "running"}}}, "php-app-4": {"pocphpmemcachedsessions-php-app-4": {"cmd": ["apache2-foreground"], "image": "pocphpmemcachedsessions_php-app-4", "labels": {"com.docker.compose.config-hash": "53a1942cef491ae6e18bd6fdf6f96ae72580626335f8d2a84f461342d82ee801", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "pocphpmemcachedsessions", "com.docker.compose.service": "php-app-4", "com.docker.compose.version": "1.8.1"}, "networks": {"pocphpmemcachedsessions_default": {"IPAddress": "172.18.0.4", "IPPrefixLen": 16, "aliases": ["php-app-4", "287f703baec0"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "links": null, "macAddress": "02:42:ac:12:00:04"}}, "state": {"running": true, "status": "running"}}}}, "changed": true}

TASK [single-node-failure : start a session on port 84 and set a replicate-test = yeap in the session] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:3
ok: [localhost] => {"cache_control": "no-store, no-cache, must-revalidate", "changed": false, "connection": "close", "content_length": "103", "content_type": "text/html; charset=UTF-8", "date": "Sun, 22 Jan 2017 14:09:12 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "msg": "OK (103 bytes)", "pragma": "no-cache", "redirected": false, "server": "Apache/2.4.10 (Debian)", "status": 200, "url": "http://localhost:84/?replicate-test=yeap", "vary": "Accept-Encoding", "x_libmemcached_version": "1.0.18", "x_powered_by": "PHP/7.0.14"}

TASK [single-node-failure : stop the replicate node for this session] **********
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:8
changed: [localhost] => {"ansible_facts": {}, "changed": true}

TASK [single-node-failure : assert that the session contains the replicate-test = yeap content] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:13
ok: [localhost] => {"cache_control": "no-store, no-cache, must-revalidate", "changed": false, "connection": "close", "content": "The session has started: a\nKey values in the session:\n    replicate-test = yeap\n", "content_length": "80", "content_type": "text/html; charset=UTF-8", "date": "Sun, 22 Jan 2017 14:09:13 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "failed": false, "failed_when_result": false, "msg": "OK (80 bytes)", "pragma": "no-cache", "redirected": false, "server": "Apache/2.4.10 (Debian)", "status": 200, "url": "http://localhost:84/", "vary": "Accept-Encoding", "x_libmemcached_version": "1.0.18", "x_powered_by": "PHP/7.0.14"}

TASK [single-node-failure : start the replicate node for this session again] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:21
changed: [localhost] => {"ansible_facts": {}, "changed": true}

TASK [single-node-failure : assert that the session contains the replicate-test = yeap content] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:26
ok: [localhost] => {"cache_control": "no-store, no-cache, must-revalidate", "changed": false, "connection": "close", "content": "The session has started: a\nKey values in the session:\n    replicate-test = yeap\n", "content_length": "80", "content_type": "text/html; charset=UTF-8", "date": "Sun, 22 Jan 2017 14:09:15 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "failed": false, "failed_when_result": false, "msg": "OK (80 bytes)", "pragma": "no-cache", "redirected": false, "server": "Apache/2.4.10 (Debian)", "status": 200, "url": "http://localhost:84/", "vary": "Accept-Encoding", "x_libmemcached_version": "1.0.18", "x_powered_by": "PHP/7.0.14"}

TASK [single-node-failure : stop the primary node for this session] ************
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:34
changed: [localhost] => {"ansible_facts": {}, "changed": true}

TASK [single-node-failure : assert that the session contains the replicate-test = yeap content] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:39
fatal: [localhost]: FAILED! => {"cache_control": "no-store, no-cache, must-revalidate", "changed": false, "connection": "close", "content": "The session has started: a\nKey values in the session:\n<br />\n<b>Warning</b>:  session_write_close(): Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (memcached-1:11211,memcached-2:11211) in <b>/var/www/html/index.php</b> on line <b>23</b><br />\n", "content_length": "310", "content_type": "text/html; charset=UTF-8", "date": "Sun, 22 Jan 2017 14:09:17 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "failed": true, "failed_when_result": true, "msg": "OK (310 bytes)", "pragma": "no-cache", "redirected": false, "server": "Apache/2.4.10 (Debian)", "status": 200, "url": "http://localhost:84/", "vary": "Accept-Encoding", "x_libmemcached_version": "1.0.18", "x_powered_by": "PHP/7.0.14"}
	to retry, use: --limit @poc-php-memcached-sessions/ansible/tests.retry

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=5    unreachable=0    failed=1
```

The important bit is in the last section of this test:
```
Warning</b>:  session_write_close(): Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (memcached-1:11211,memcached-2:11211) in <b>/var/www/html/index.php</b> on line <b>23</b><br />\n
```

Where it fails to retrieve session content from the secondary Memcached node after the primary node is killed.

**Comment by sodabrew** [comment] 2017-01-24 10:40
I'm not going to block the 3.0.0 release on this, but it does look like it needs to be investigated and fixed, based on your thorough bug report.

**Comment by SjonHortensius** [comment] 2017-01-24 11:02
I have investigated this together with @arjenschol. This was caused by https://github.com/php/php-src/commit/224aaf94af8f06a241d023bf58533dc6db6d9d1f#diff-52eb9eb7f9d5d9125fbb1337a6541c06R560 and I'm pretty sure it's fixed in https://github.com/php-memcached-dev/php-memcached/commit/bd321830676d7e313b4b39bec6fbeb6ec9f9f7d8

However, that commit has been on master for a while so it's weird this bug would still occur

**Comment by jaimievansanten** [comment] 2017-01-24 15:39
Same result when running the suite against latest `upstream/master`: (was testing against older php7 branch before, my bad)

```
TASK [single-node-failure : assert that the session contains the replicate-test = yeap content] ***
task path: poc-php-memcached-sessions/ansible/roles/single-node-failure/tasks/main.yml:39
fatal: [localhost]: FAILED! => {"cache_control": "no-store, no-cache, must-revalidate", "changed": false, "connection": "close", "content": "The session has started: a\nKey values in the session:\n<br />\n<b>Warning</b>:  session_write_close(): error saving session to memcached: (0x7fdc0aa67000) getaddrinfo() or getnameinfo() HOSTNAME LOOKUP FAILURE, Name or service not known,  host: memcached-1:11211 -&gt; libmemcached/connect.cc:242 in <b>/var/www/html/index.php</b> on line <b>23</b><br />\n<br />\n<b>Warning</b>:  session_write_close(): Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (memcached-1:11211,memcached-2:11211) in <b>/var/www/html/index.php</b> on line <b>23</b><br />\n", "content_length": "609", "content_type": "text/html; charset=UTF-8", "date": "Tue, 24 Jan 2017 12:53:22 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "failed": true, "failed_when_result": true, "msg": "OK (609 bytes)", "pragma": "no-cache", "redirected": false, "server": "Apache/2.4.10 (Debian)", "status": 200, "url": "http://localhost:84/", "vary": "Accept-Encoding", "x_libmemcached_version": "1.0.18", "x_powered_by": "PHP/7.0.14"}
	to retry, use: --limit poc-php-memcached-sessions/ansible/tests.retry
```

Colleague is working to get the test suite open-sourced so that it'll be much easier to reproduce.

**Comment by jappievw** [comment] 2017-01-24 15:53
Just got some time to make it easier for you guys to run the test suite we created. It is documented as well. Please find it here: https://github.com/jappievw/poc-php-memcached-client-side-session-replication.

**Comment by sodabrew** [comment] 2017-01-25 21:58
What version of libmemcached are you using, by the way?

**Comment by jaimievansanten** [comment] 2017-01-25 22:05
1.0.18 (there's an additional header in the output of index.php to output the used libmemcached version): `X-Libmemcached-Version`

**Comment by sodabrew** [comment] 2017-01-25 22:37
Sorry, I totally missed that you already provided that info!

**Comment by tersmitten** [comment] 2017-04-20 14:14
Any updates on this?

**Comment by jappievw** [comment] 2017-04-20 15:42
No updates from our side

**Comment by Vincent--** [comment] 2017-05-22 13:31
I have the same issue... Our website randomly issues:

```
Noticed exception 'ErrorException' with message 'Warning: session_start(): error getting session from memcached: (0x7f3f5949c5b0) A TIMEOUT OCCURRED, (number_of == 0),  host: 192.168.221.42:11211 -&gt; libmemcached/connect.cc:133' 
```

or

```
Noticed exception 'ErrorException' with message 'Warning: Unknown: Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (192.168.221.41:11211?persistent=1,192.168.221.42:11211?persistent=1)'
```

These werent present before we php5.6

**Comment by Vincent--** [comment] 2017-05-22 13:33
And I don't use any replication

```
#php --ri session

session

Session Support => enabled
Registered save handlers => files user memcache memcached
Registered serializer handlers => php_serialize php php_binary igbinary msgpack wddx

Directive => Local Value => Master Value
session.auto_start => Off => Off
session.cache_expire => 180 => 180
session.cache_limiter => nocache => nocache
session.cookie_domain => no value => no value
session.cookie_httponly => Off => Off
session.cookie_lifetime => 0 => 0
session.cookie_path => / => /
session.cookie_secure => Off => Off
session.entropy_file => /dev/urandom => /dev/urandom
session.entropy_length => 32 => 32
session.gc_divisor => 1000 => 1000
session.gc_maxlifetime => 28800 => 28800
session.gc_probability => 0 => 0
session.hash_bits_per_character => 5 => 5
session.hash_function => 0 => 0
session.lazy_write => Off => Off
session.name => PHPSESSID => PHPSESSID
session.referer_check => no value => no value
session.save_handler => memcached => memcached
session.save_path => 192.168.221.41:11211?persistent=1,192.168.221.42:11211?persistent=1 => 192.168.221.41:11211?persistent=1,192.168.221.42:11211?persistent=1
session.serialize_handler => php => php
session.upload_progress.cleanup => On => On
session.upload_progress.enabled => On => On
session.upload_progress.freq => 1% => 1%
session.upload_progress.min_freq => 1 => 1
session.upload_progress.name => PHP_SESSION_UPLOAD_PROGRESS => PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix => upload_progress_ => upload_progress_
session.use_cookies => On => On
session.use_only_cookies => On => On
session.use_strict_mode => Off => Off
session.use_trans_sid => 0 => 0
```

```
#php --ri memcached

memcached

memcached support => enabled
Version => 3.0.3
libmemcached version => 1.0.18
SASL support => yes
Session support => yes
igbinary support => yes
json support => yes
msgpack support => yes

Directive => Local Value => Master Value
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.compression_type => fastlz => fastlz
memcached.default_binary_protocol => 0 => 0
memcached.default_connect_timeout => 0 => 0
memcached.default_consistent_hash => 0 => 0
memcached.serializer => igbinary => igbinary
memcached.sess_binary_protocol => 1 => 1
memcached.sess_connect_timeout => 0 => 0
memcached.sess_consistent_hash => 1 => 1
memcached.sess_lock_expire => 0 => 0
memcached.sess_lock_max_wait => not set => not set
memcached.sess_lock_retries => 5 => 5
memcached.sess_lock_wait => not set => not set
memcached.sess_lock_wait_max => 2000 => 2000
memcached.sess_lock_wait_min => 1000 => 1000
memcached.sess_locking => 0 => 0
memcached.sess_number_of_replicas => 0 => 0
memcached.sess_persistent => 1 => 1
memcached.sess_prefix => memc.sess.key. => memc.sess.key.
memcached.sess_randomize_replica_read => 0 => 0
memcached.sess_remove_failed_servers => 0 => 0
memcached.sess_sasl_password => no value => no value
memcached.sess_sasl_username => no value => no value
memcached.sess_server_failure_limit => 0 => 0
memcached.store_retry_count => 2 => 2
```

**Comment by tersmitten** [comment] 2017-05-22 13:34
`?persistent=` does not work anymore

**Comment by Vincent--** [comment] 2017-05-22 13:45
I know, I've opened an issue related to that. But the param is set in the php conf too, so that should be the cause of the issue

**Comment by chris1312** [comment] 2017-10-17 11:56
@jaimievansanten @Vincent-- any updates on this issue? I face the same issue random.

I am using:
PHP 7.1.4 
libmemcached 1.0.18

**Comment by semenovtm** [comment] 2018-03-27 07:06
Same issue.

AppException: session_start(): error getting session from memcached: (0x563774d660a0) A TIMEOUT OCCURRED, (number_of == 0),  host: xx.xx.xx.xx -&gt; libmemcached/connect.cc:133

**Closed** 2020-03-18 17:23 UTC
