### ISSUE TITLE
BashOnWindows - and data memory limit of 8136 bytes 

### ISSUE THREAD

**Issue by spagu** [php-memcached-dev/php-memcached#332] opened 2017-02-22 01:32 UTC
_From @spagu on February 22, 2017 0:29_

Memcached seems to have hard limit for storing object larger than 8136 bytes. This was confirmed on several computers with windowsbash with ubuntu 14 and  ubuntu 16. 
Changing -I parameter has no effect. STATS looks normal and exactly the same as on clean linux machines where it works fine.

version of memcached: 1.4.14 and 1.4.25 

PHP version: 7.0.16-2+2deb.sury.org~trusty+1 with standard extension php-memcached pecl version 3.0.3 (not old memcache)
```
<?php
$data = "generate string longer than 8136 characters";
$client = new Memcached();
$client->addServer('memcache', 11211, 0);
$client->set('mykey',$data);
echo $client->getResultCode();
?>
```

expected result:
0

actual result:
38

When using NC this works fine. 

_Copied from original issue: memcached/memcached#261_

**Comment by spagu** [comment] 2017-02-22 01:32
_From @dormando on February 22, 2017 0:32_

I wouldn't know where to start looking. :/ Try a different language/client or manually set some value via netcat? What php client is that, even?

**Comment by sodabrew** [comment] 2017-02-22 04:23
This is not an expected limit.

**Comment by spagu** [comment] 2017-02-22 08:49
any way to debug it deeper? to find out where the limit was defined? I found exactly the same limit on 3 computers with different specs. I am not sure if this is extension or php itself.

**Comment by sodabrew** [comment] 2017-02-22 09:34
This limit is not defined and is not expected. You should not have a problem with larger values.

Could you try adding to your test script:
```
$client->setOption(Memcached::OPT_COMPRESSION, 0);
```

Let's see if maybe there's a problem with the compression step. By default this kicks in for items over a 100 bytes.

**Comment by sodabrew** [comment] 2017-02-27 17:41
Were you able to change the compression settings to see if that helped?

**Comment by sodabrew** [comment] 2017-05-16 23:33
Closing because the issue cannot be confirmed.

**Closed by sodabrew** 2017-05-16 23:33 UTC
